### ISSUE TITLE
Improve Composer scripts

### ISSUE THREAD

**Issue by szepeviktor** [infinum/eightshift-libs#333]
### Describe your feature request

Composer is very witty.
Even on Windows!!

### Describe the solution you'd like

Was.

` "test:unit": "@php ./vendor/bin/pest --group=unit",`

Could be.

` "test:unit": "pest --group=unit",`

### Please confirm that you have searched existing issues in this repo.

No

### Please confirm that you have searched in our documentation and couldn't find the answer.

No

**Comment by dingo-d** [comment]
The [`@php`](https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts) part of the composer script ensures that the script will use the current php process for execution, so I'd leave it in.

As for using binaries instead of their full path, that's just to safeguard things failing on Windows (IIRC). I'd need to test on Windows (not WSL) to see if this won't fail. I know that there was an issue on WPCS, and similar proposal was rejected because of Windows issue.

**Comment by szepeviktor** [comment]
If there is an issue with Composer on Windows please let me open an issue at Composer.

**Comment by dingo-d** [comment]
I have installed PHP8 and composer on my Windows machine and required the wpcs package. When typing `phpcs -i` I get 

> 'phpcs' is not recognized as an internal or external command, operable program or batch file.

vs when I type `vendor\bin\phpcs -i` I get 

> The installed coding standards are MySource, PEAR, PSR1, PSR2, PSR12, Squiz and Zend

<img width="572" alt="image" src="https://user-images.githubusercontent.com/8638515/186604307-c875f084-d29e-4532-b876-b0a0ae2f532b.png">

I've also cloned the repo and tried running phpstan via command when I have vendor in the script and without it:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/8638515/186605891-29f67aeb-0783-452a-a9cc-7a8c7d8ce4d4.png">

I think the `@php` in front of the command will cause the above output because when removing it, I do get the tests to run and phpstan to run as well. 

So maybe that's something to consider reporting to Composer (if it's unexpected behavior).

**Comment by szepeviktor** [comment]
> So maybe that's something to consider reporting to Composer (if it's unexpected behavior).

Composer prepend bin-dir to `$PATH`.
Please see the purple callout https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

**Comment by szepeviktor** [comment]
As for `@php phpstan analyze` I think this is not intended usage.
The script `phpstan analyze` would successfully execute.

**Comment by szepeviktor** [comment]
Too 🔥 hot topic for viktor!

**Comment by dingo-d** [comment]
I guess we can simplify the command then (drop the `@php` and just use the binaries without pointing to the `vendor/bin/` dir) 👍🏼
