### ISSUE TITLE
shortcode

### ISSUE THREAD

**Issue by marijang** [infinum/eightshift-libs#79]
How do I execute shortcode in custom component?
... shortcode( '[mc4wp_form id="'.$id.'"]' ); This not works for example
Thanks

**Comment by IvanGrginovInf** [comment]
Hi @marijang , 

Possibly stupid question, have you echoed it? `echo do_shortcode( '[mc4wp_form id="'.$id.'"]' )`. 

There's no reason I know of that would prevent shortcodes from working but then again this was never considered / tested since we don't use shortcodes. You can maybe try it on a component that's echoed using `wp_kses_post()` but other than that I have no useful suggestions.

If you find the reason why shortcodes don't work and a fix , a PR would be most welcome.

**Comment by marijang** [comment]
i find why

I' m using mailchimp shortcode....
like:
echo  wp_kses_post(Components::render( 'mailchimp', [ ....

change to..
echo  Components::render( 'mailchimp', [

it works.
There is js code inside shortcode....

Thanks

**Comment by IvanGrginovInf** [comment]
Awesome! Even tho it's unsafe to have unfiltered components, it can't really be helped if this requires some 3rd party JS that Mailchimp's shortcode outputs (you'd have to allow the `script` tag either way for it to work).

Generally it would be a good idea / practice to write your own `wp_kses()` that allows only the tags added by the Mailchmp shortcode and nothing.

https://developer.wordpress.org/reference/functions/wp_kses/

Closing issue, resolved.
